version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    volumes:
      - ./src/backend:/app
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase
    env_file:
      - ./src/backend/.env
    depends_on:
      - mongodb
    networks:
      - app-network

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    volumes:
      - ./src/frontend:/app
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://backend:5000
    env_file:
      - ./src/frontend/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
