# Використовуйте офіційний базовий образ для Python
# FROM python:3.8-slim

# Використовуйте офіційний базовий образ для Node.js
# FROM node:14-alpine

# Використовуйте офіційний базовий образ для .NET Core
# FROM mcr.microsoft.com/dotnet/core/sdk:3.1

# Встановіть робочу директорію в контейнері
WORKDIR /app

# Скопіюйте файли проекту в контейнер
COPY . .

# Встановіть залежності
# Для Python
# RUN pip install --no-cache-dir -r requirements.txt

# Для Node.js
# RUN npm install

# Для .NET Core
# RUN dotnet restore

# Запустіть додаток
# Для Python
# CMD ["python", "app.py"]

# Для Node.js
# CMD ["node", "app.js"]

# Для .NET Core
# CMD ["dotnet", "run"]
